/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import clases.Conexion;
import clases.verificador;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author wili_
 */
public class buscador extends javax.swing.JFrame {

    /**
     * Creates new form buscador
     */
    DefaultTableModel model = new DefaultTableModel();

    public buscador() {
        initComponents();
        jTable_compras = new JTable(model);
        jScrollPane1.setViewportView(jTable_compras);

        model.addColumn("Nr compra");
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Precio_unitario");
        model.addColumn("cantidad");
        model.addColumn("Total");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        texto_buscado = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_compras = new javax.swing.JTable();
        txt_total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("agregar_producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));
        getContentPane().add(texto_buscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 150, 30));

        txt_cantidad.setText("1");
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 90, 30));

        jTable_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_compras);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 250));

        txt_total.setText("0.0");
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 90, 40));

        jLabel1.setText("Total a pagar :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 80, 20));

        jLabel2.setText("id_producto ;");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, 10));

        jLabel3.setText("cantidad :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 60, 20));

        jButton2.setText("Vender");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id = 0;
        verificador ver = new verificador();
        double algo = 0.0;

        if (ver.esNumero(texto_buscado.getText())|| texto_buscado.getText()!=null) {
                
        } else {
            JOptionPane.showMessageDialog(null, "Porfavor, inserte el codigo del producto");
            
        }
        try {
            Connection cn = Conexion.conectar();        // Preparar la sentencia SQL con un placeholder para la variable de búsqueda
            String sql = "SELECT id, name, sale_price FROM product WHERE id = ?";
            PreparedStatement stmt = cn.prepareStatement(sql);

            // Establecer el valor del placeholder
            stmt.setString(1, texto_buscado.getText().trim());
            // Ejecutar la consulta y obtener el resultado
            ResultSet rs = stmt.executeQuery();
            int h = 1;

            while (rs.next()) {
                //resultado.setText();
                id = rs.getInt("id");
                //nombreProducto = rs.getString("name");
                //description = rs.getString("description");

                Object[] fila = new Object[6];
                fila[0] = h;
                for (int i = 1; i < 4; i++) {
                    fila[i] = rs.getObject(i);
                    /*if(i=){
                    
                    }*/
                }
                h++;
                fila[4] = txt_cantidad.getText();
                fila[5] = Double.parseDouble(fila[4].toString()) * Double.parseDouble(fila[3].toString());
                model.addRow(fila);
            }
        } catch (Exception E) {
            JOptionPane.showMessageDialog(null, "Error" + E);
        }
        TableModel model = jTable_compras.getModel();

// Inicializar la variable de suma
        double sum = 0;

// Recorrer todas las filas del JTable
        for (int i = 0; i < model.getRowCount(); i++) {
            // Obtener el valor de la celda de la columna deseada en la fila actual
            double value = Double.parseDouble(model.getValueAt(i, 5).toString());
            // Sumar el valor al total
            sum += value;
        }
        

// Utilizar el valor total de la suma para lo que necesites
        System.out.println("La suma total de la columna es: " + sum);
        sum = Math.round(sum * 100.0) / 100.0;
        txt_total.setText(Double.toString(sum));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_compras;
    private javax.swing.JTextField texto_buscado;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
