/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.*;

/**
 *
 * @author wili_
 */
public class crear_producto extends javax.swing.JFrame {

    /**
     * Creates new form crear_producto
     */
    public crear_producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_description = new javax.swing.JTextField();
        txt_purchase_price = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        txt_sale_price = new javax.swing.JTextField();
        txt_imagen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 30, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabel2.setText("name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabel3.setText("description");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabel4.setText("Stock");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabel5.setText("purchese_price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabel6.setText("sale_price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabel7.setText("imagen");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 110, -1));

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 110, -1));

        txt_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descriptionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 110, -1));

        txt_purchase_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_purchase_priceActionPerformed(evt);
            }
        });
        getContentPane().add(txt_purchase_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 110, -1));

        txt_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stockActionPerformed(evt);
            }
        });
        getContentPane().add(txt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 110, -1));

        txt_sale_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sale_priceActionPerformed(evt);
            }
        });
        getContentPane().add(txt_sale_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 110, -1));

        txt_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_imagenActionPerformed(evt);
            }
        });
        getContentPane().add(txt_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 110, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_imagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_imagenActionPerformed

    private void txt_sale_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sale_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sale_priceActionPerformed

    private void txt_purchase_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_purchase_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_purchase_priceActionPerformed

    private void txt_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stockActionPerformed

    private void txt_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descriptionActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try{
              
              Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/dry","root","");
              PreparedStatement pst = cn.prepareStatement("insert into product value(?,?,?,?,?,?,?)");
            FileInputStream input = null;           
                input = new FileInputStream(new File("C:\\Users\\wili_\\Documents\\NetBeansProjects\\dry_1\\src\\front\\homev2 (1).jpg"));
            
              pst.setString(1,"0");
              pst.setString(2,txt_name.getText().trim());
              pst.setString(3,txt_description.getText().trim());
              pst.setDouble(4,Double.parseDouble(txt_purchase_price.getText()));
              System.out.print("llegamos");
              pst.setInt(5,Integer.parseInt(txt_stock.getText()));
              System.out.print("llegamos");
              pst.setDouble(6,Double.parseDouble(txt_sale_price.getText()));
              pst.setBinaryStream(7, input);
              System.out.print("llegamos");
              pst.executeUpdate();
              txt_id.setText ("");
              txt_name.setText ("");
              txt_description.setText ("");             
              txt_purchase_price.setText ("");
              txt_stock.setText ("");
              txt_sale_price.setText ("");             
              txt_imagen.setText ("");
          }catch (FileNotFoundException | SQLException ex) {
            System.err.println(ex.getMessage());
            /*
           id,description,xt_purchase,tock,sle_price           
            
            
                   */
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crear_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crear_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crear_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crear_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crear_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_imagen;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_purchase_price;
    private javax.swing.JTextField txt_sale_price;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
